### ISSUE TITLE
TypeError invalid input

### ISSUE THREAD

**Issue by christianmagill** [claflamme/axegrinder#5]
I'm receiving the following error.

```
$ axegrinder crawl https://www.adventhealthheartcareeastfl.com/ --csv=file.csv                                                               [9:10:17]

--- Building sitemap. This might take a bit...

/usr/local/lib/node_modules/axegrinder/node_modules/urijs/src/URI.js:1253
      throw new TypeError('invalid input');
      ^

TypeError: invalid input
    at URI.p.href (/usr/local/lib/node_modules/axegrinder/node_modules/urijs/src/URI.js:1253:13)
    at new URI (/usr/local/lib/node_modules/axegrinder/node_modules/urijs/src/URI.js:70:10)
    at URI (/usr/local/lib/node_modules/axegrinder/node_modules/urijs/src/URI.js:46:16)
    at /usr/local/lib/node_modules/axegrinder/node_modules/simplecrawler/lib/crawler.js:1744:24
    at FetchQueue.oldestUnfetchedItem (/usr/local/lib/node_modules/axegrinder/node_modules/simplecrawler/lib/queue.js:250:13)
    at Crawler.crawl (/usr/local/lib/node_modules/axegrinder/node_modules/simplecrawler/lib/crawler.js:1738:19)
    at /usr/local/lib/node_modules/axegrinder/node_modules/simplecrawler/lib/crawler.js:457:21
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by iris00** [comment]
+1
